version: '3'
services:
  postgres:
    image: postgres:14.10
    ports:
      - "1313:1313"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER-denis}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD-ss991929}
      POSTGRES_DB: ${POSTGRES_DB_NAME-books}
